###############################################################################################
set -u

# Argument = -i input -c chunksize -D blast-database -v
usage() {
  cat <<EOF
  usage: $0 options
  
  ###############################################################################
  This tool calculates read counts on a template of choice. It reportes the 
  counts for both, the sense and the antisense strand.
  
  usage: [PATH]/selectUTRs [options] -F 
  
  OPTIONS:
      -h  Show this message
      -A  assembly fasta file to be scaffolded
          results will be depostied into the very same directory of the fasta file
      -x  assembly gfa
          if available this file will be used to assis SALSA scaffolding
      -V  assembly Version
      -N  Name for the scaffolding run
      -r  path to raw-paired end HiC data file generated by the AnnotationPipeline
            please import via AnnotationPipeline using option -P 
      -G  Genotype for assembly
      -n  path to naopore fasta sequence file for gap-filling
            optional - otherwise files will be filtered from all reads within
            the pipeline
      -C  set flag for local processing (use only if multiple cores available)
      -a  analyze all libraries for genotype
      -D  set debug mode - does not trigger git commit
      -g  only run gap-filling on supplied assembly
      -F  rerun generation of HiC mappings
      -R  rerun gap-filling part of the pipeline from scratch
      -w  completely wipe all old data and start fresh
EOF
}

assemblyFASTA=
GFA=
assemblyVERSION=
scaffoldingNAME=
rawFASTA=
GENOTYPE=
NANOPOREreads=
COMPUTING=C
ALL=
DEBUG=N
GAPFILLonly=N
FORCE=
WIPE=
RERUN=

while getopts ÒhA:V:N:r:G:n:CaDgFwR,Ó OPTION; do
  case $OPTION in
  h)
    usage
    exit 1
    ;;
  A)
    assemblyFASTA=$OPTARG
    ;;
  x)
    GFA=$OPTARG
    ;;
  V)
    assemblyVERSION=$OPTARG
    ;;
  N)
    scaffoldingNAME=$OPTARG
    ;;
  r)
    rawFASTA=$OPTARG
    ;;
  G)
    GENOTYPE=$OPTARG
    ;;
  n)
    NANOPOREreads=$OPTARG
    ;;
  C)
    COMPUTING=L
    ;;
  a)
    ALL=A
    ;;
  D)
    DEBUG=Y
    ;;
  g)
    GAPFILLonly=Y
    ;;
  F)
    FORCE=Y
    ;;
  w)
    WIPE=Y
    ;;
  R)
    RERUN=Y
    ;;
  ?)
    usage
    exit
    ;;
  esac
done

###################################################################################################

#dm6 reference genome for Nanoplot quality assesment
refGenome=
#location of the raw-data (top folder containing all runs)
RAW=
#supply basecall version of data for polishing
BCversion=

#extract base-path from input fasta
if [[ -z $scaffoldingNAME ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "       Please provide scaffoldingNAME in option N!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi
if [[ -z $assemblyVERSION ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "       Please provide assembly version in option V!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi
if [[ -z $rawFASTA ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "    Please provide rawFASTA with the path to the HiC data in option r!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi
if [[ ! -z $NANOPOREreads && ! -s $NANOPOREreads ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "    Provided file for Nanopore reads does not exist r!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi
if [[ -z $GENOTYPE ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "       Please provide Genotype in option G!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi
#extract base-path from input fasta
if [[ ! -s $assemblyFASTA ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "       Provided assembly-FASTA does not exist r!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi
if [[ -z $assemblyFASTA ]]; then
  #usage
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
  printf "       Please provide assemblyFASTA in option A!\n"
  printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n"
  exit
fi

ASSEMBLYdir=$(dirname $assemblyFASTA)
assemblyNAME=$(basename -- "$assemblyFASTA")
assemblyNAME="${assemblyNAME%.*}"
#TMPdir="${SCRATCHDIR}/nanopore/polished-assembly/${scaffoldingNAME}_$assemblyNAME/"
if [[ $GAPFILLonly == Y ]]; then 
  TMPdir=
  OPENdir="${ASSEMBLYdir}/gapFILL_$assemblyNAME/${scaffoldingNAME}/"
else
  TMPdir=
  OPENdir="${ASSEMBLYdir}/scaffold_$assemblyNAME/${scaffoldingNAME}/"
fi
#@!@#
#separator for printing of settings to log
###################################################################################################
#variable-setup
DATE_OF_DAY=$(date +%F)
FULL_DATE=$(date)
#DATE_OF_DAY=2017-02-14

#wipe everything if requested
if [[ $WIPE == Y ]]; then
  rm -rf $OPENdir
  rm -rf $TMPdir
fi

mkdir -p $OPENdir

VERSION=$(ls -l ${OPENdir} | wc -l)
VERSION="V$VERSION"

SINGULARITYdir=${TMPdir}singu/

mkdir -p $OPENdir
mkdir -p $TMPdir
mkdir -p $SINGULARITYdir

###################################################################################################
#preset scripts

#determine script-location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SCRIPTdirRAW="$(cd -P "$(dirname "$SOURCE")" && pwd)"
SCRIPTdirRAW="${SCRIPTdirRAW}/"
SCRIPTdir="${SCRIPTdirRAW}script-files/"
UTILITYdir="${SCRIPTdirRAW}utility-files/"

#move scripts to TMP-directory
rm -rf ${TMPdir}script-files
cp -r ${SCRIPTdir} ${TMPdir}script-files
SCRIPTdir=${TMPdir}script-files/

mv ${TMPdir}script-files/main.sh ${TMPdir}script-files/SCAFF-${scaffoldingNAME}

###############################################################################################
#download all singularity images required

cd ${SINGULARITYdir}
# singularity pull --name flye.app shub://singularity.vbc.ac.at/brenneckelab/flye:v2.7

wget -O MARVEL.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/MARVEL.app
wget -O minimap2.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/minimap2.app
wget -O basicTools.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/basicTools.app
wget -O HiCAssembler.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/HiCAssembler.app
wget -O SALSA.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/SALSA.app
wget -O wtdbg2.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/wtdbg2.app
wget -O ragtag.app https://brenneckelab.imba.oeaw.ac.at/Publication_Data/2025_Handler_OSC-genome/Apptainer/ragtag.app

###################################################################################################
#report settings and initiate log-files

printf "Analysis start DATE+TIME = ${FULL_DATE}\n" >>"${OPENdir}log.txt"

cd ${SCRIPTdirRAW}

if [[ $DEBUG != Y ]]; then

  #ask for commit-message
  while true; do
    read -r -p "Plese specify a commit-message: " msg
    case $msg in
    [Nn]) break ;;
    *)
      commitMESSAGE=$msg
      break
      ;;
    esac
  done

  #commit all changes
  git add .
  if [[ -z $commitMESSAGE ]]; then
    git commit -m "automatic commit on submission"
  else
    git commit -m "$commitMESSAGE"
  fi
  #git push --all
fi
commitID=$(git log -1 --pretty=format:"%h")

printf "\n\n############################################################################\n\n" >>"${OPENdir}log.txt"
printf "CommitID= ${commitID}\n\n" >>"${OPENdir}log.txt"

###################################################################################################

#determine available RUNs for current genotype and molecule type
ls -l ${RAW} | grep ${GENOTYPE} | grep DNA | awk -v OFS="\t" '{print NR, $NF}' >${TMPdir}available_runs.txt
cat ${TMPdir}available_runs.txt

#ask user for input
if [[ -z $NANOPOREreads ]]; then
  rm -rf ${TMPdir}selected-runs.txt
  while true; do
    if [[ -z $ALL ]]; then
      read -p "Which Nanopore Run's to analyze? [# in list above or comma separate list or A for all]" NR
    else
      NR=$ALL
    fi
    case $NR in
    [1-9] | [1-9][0-9])
      cat ${TMPdir}available_runs.txt | awk -v locTMP=${TMPdir} -v xNR=$NR ' BEGIN {xswitch=0}; 
             { if($1==xNR) { xswitch=1; print "RUN \""$0"\" selected"; print $NF > locTMP "selected-run.txt" } }
                  END { print xswitch > locTMP"switch.txt"}' | tr '\t' ' '
      switch=$(cat ${TMPdir}switch.txt)
      if [[ $switch == 1 ]]; then
        RUNs=$(cat ${TMPdir}selected-run.txt)
        break
      else
        cat ${TMPdir}available_runs.txt
        printf "\nplease select existing run \n\n"
      fi
      ;;
    [Aa])
      RUNs=$(cat ${TMPdir}available_runs.txt | cut -f 2 | tr '\n' '\t')
      break
      ;;
    *)
      echo $NR | awk -v INFILE=${TMPdir}available_runs.txt -v OUTFILE=${TMPdir}selected-runs.txt '
                      BEGIN{
                        while((getline RAW_LINES < INFILE) > 0) {split(RAW_LINES,splitLINES,/\t| /); availSELECTION[splitLINES[1]]=splitLINES[2] }
                        EXIT="Y"
                      } 
                      { 
                        N=split($1, X, /,/)
                        if( N==1) {
                          print  "\n\n\nplease supply runs in a valid comma separated format"
                        }else{
                          for( i in X){
                            if( X[i] in availSELECTION ) {
                              if(OUTSTRING==""){
                                OUTSTRING=availSELECTION[X[i]]
                              }else{
                                OUTSTRING=OUTSTRING" "availSELECTION[X[i]]
                              }
                            }else{
                              print "selected run #"X[i]" not available for selection" 
                              EXIT=N
                            }
                          }
                          if(EXIT == "Y" ){
                            print OUTSTRING > OUTFILE 
                          }
                        }
                      }'
      if [[ -f ${TMPdir}selected-runs.txt ]]; then
        RUNs=$(cat ${TMPdir}selected-runs.txt)
        break
      fi
      ;;

    esac

  done

  subRUNs=$(echo $RUNs | tr ' ' '\t' | tr '\t' '~')
else
  subRUNs=""
fi
###################################################################################################
mkdir -p ${OPENdir}settings/
cat ${SCRIPTdirRAW}*.sh |
  awk -v RS="#@!@#" '{if (NR==1) print }' >${OPENdir}settings/SETTINGS_${commitID}.log

TIME="$(date "+%s")"

###################################################################################################
#submit main-run script
LOG=${OPENdir}/LOGs/
#@ rm -rf ${LOG}/*
mkdir -p ${LOG}
cd $LOG

echo $OPENdir
echo $TMPdir

COMMAND="${SCRIPTdir}SCAFF-${scaffoldingNAME}"
VARI="OPENdir=${OPENdir},TMPdir=${TMPdir},SINGULARITYdir=${SINGULARITYdir},COMPUTING=${COMPUTING},SCRIPTdir=${SCRIPTdir},UTILITYdir=${UTILITYdir},LOG=${LOG},scaffoldingNAME=${scaffoldingNAME},assemblyNAME=${assemblyNAME},FORCE=${FORCE},RERUN=${RERUN},assemblyFASTA=${assemblyFASTA},GFA=${GFA},rawFASTA=${rawFASTA},NANOPOREreads=${NANOPOREreads},RAW=${RAW},subRUNs=${subRUNs},BCversion=${BCversion},assemblyVERSION=${assemblyVERSION},GAPFILLonly=${GAPFILLonly}"

echo $VARI
#module load slurm/17.02.10
echo computing $COMPUTING
if [[ $COMPUTING == C ]]; then
  sbatch $COMMAND ${VARI}
else
  if [[ -z ${SLURM_JOBID+x} ]]; then
    srun --cpus-per-task=10 --mem=20g --qos=short $COMMAND ${VARI}
  else
    $COMMAND ${VARI}
  fi
fi

exit
